add fuction giveup
emanuelturtula/t3p-client pull request #15
Opened 2021-03-24 21:21 UTC by geroferrari

2021-03-25 00:22 UTC, emanuelturtula commented on headers/types.h
> +    IN_A_GAME
Me parece que queda mas lindo "IN_GAME"

2021-03-25 00:24 UTC, emanuelturtula commented on cpp/tcp.cpp
> +    sprintf(message, "GIVEUP \r\n \r\n");
Esto podria remplazarse por const char* message = "GIVEUP \r\n \r\n". La idea del sprintf es usarlo no mas cuando hay que formatear el string con alguna variable. Por ejemplo, cuando se manda un invite, el nombre del jugador es una variable, entonces no podemos saber de antemano como es el string. Pero en este caso, se manda siempre el mismo mensaje

2021-03-25 00:25 UTC, emanuelturtula requested changes
Fijate los comentarios que te agregué Gero, son 2 pavadas para cambiar

2021-04-08 02:05 UTC, geroferrari commented on headers/types.h
> +    IN_A_GAME
agree!

2021-04-08 02:05 UTC, geroferrari commented on cpp/tcp.cpp
> +    sprintf(message, "GIVEUP \r\n \r\n");
my bad

2021-04-09 22:57 UTC, emanuelturtula approved these changes

2021-04-09 22:57 UTC, merged